name: build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TAGS: 1.23.3,latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: docker login to docker.io
        uses: docker/login-action@v2
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: docker login to ghcr.io
        uses: docker/login-action@v2
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup binfmt-support
        uses: docker/setup-qemu-action@v2

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Generate push tags
        run: |
          dockerhub_tags=$(echo $TAGS | tr ',' '\n' | sed -e 's#^#docker.io/${{ secrets.DOCKERHUB_USER }}/nginx-quic:#g' | tr '\n' ',' | sed 's#,$##')
          ghcr_tags=$(echo $TAGS | tr ',' '\n' | sed -e 's#^#ghcr.io/nginx-quic/nginx-quic:#g' | tr '\n' ',' | sed 's#,$##')
          echo "PUSH_TAGS=${dockerhub_tags},${ghcr_tags}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: ${{ env.PUSH_TAGS }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
